export { Client, EmailsService, attachmentFromBytes } from "./client.js";
export {
  MailnationError,
  isMailnationError,
  isUnauthorized,
  isNotFound,
  isInsufficientCredits,
  isRateLimited,
  isIdempotencyConflict,
  isIdempotencyInProgress,
  isRetryable,
  CodeInvalidRequest,
  CodeUnauthorized,
  CodeForbidden,
  CodeNotFound,
  CodeConflict,
  CodeInsufficientCredits,
  CodeRateLimited,
  CodeWarmupLimited,
  CodeAccountSuspended,
  CodePayloadTooLarge,
  CodeServiceUnavailable,
  CodeTemporaryFailure,
  CodeInternalError,
  CodeIdempotencyConflict,
  CodeIdempotencyInProgress,
} from "./errors.js";
export {
  DEFAULT_BASE_URL,
  StatusQueued,
  StatusDelivered,
  StatusPartial,
  StatusFailed,
} from "./types.js";
export type {
  Addresses,
  Attachment,
  AttachmentMeta,
  SendRequest,
  SendResponse,
  Recipient,
  Email,
  ClientOptions,
  WaitOptions,
} from "./types.js";
